### ISSUE TITLE
新浪微博是怎么配置key呢？

### ISSUE THREAD

**Issue by s3hengwu** [Bilibili/BiliShare#1]
新浪微博是怎么配置key呢？

**Comment by s3hengwu** [comment]
我在这个类找到ConfigHelper， 是在这个类里配置吧

**Comment by Jungerr** [comment]
SharePlatformConfigHelper.configSina(String appKey).  (参考ShareHelper和ConfigHelper类)

另外可以通过如下方法来配置新浪redirectUrl和scope信息：
BiliShareConfiguration configuration = new BiliShareConfiguration.Builder(context)
                .sina( redirectUrl,  scope)
                ..........
                .build();

**Comment by s3hengwu** [comment]
还有一个意见反馈，要是能添加登录模块就完美了！！！

**Comment by Jungerr** [comment]
即使做社会化登录，也不会添加到这个库里面。对于不需要登录模块的人来说，这个库会显得臃肿。
