### ISSUE TITLE
只能用作BaseShareableActivity，能用作Fragment 获取 其他组件里面吗

### ISSUE THREAD

**Issue by starktonys** [Bilibili/BiliShare#10]
只能用作BaseShareableActivity，能用作Fragment 获取 其他组件里面吗

**Comment by starktonys** [comment]
PopFullScreenSharePlatformSelector 里面的Context写死了，应该写成接口形式Context

**Comment by alvince** [comment]
BaseShareableActivity 是示范 ShareHelper 的调用和封装，实际使用可以单独使用一个 Activity 作为分享操作实现的容器，分享相关选项使用 Intent 参数传递；
按照示例的继承方式也没问题，至于 Fragment 使用的话，可以定义接口来代理，毕竟 Fragment 的使用还是在 Activity 内部的

关于 Selector ... 个人看法这个模块主要的作用还是示例，毕竟写的太粗糙，实际使用大概都是有各自的需求驱动选择面板的，像 UI, Channels 配置 还有选择逻辑什么的

**Comment by Jungerr** [comment]
@alvince 说得对，Selector只是个示例。
