### ISSUE TITLE
大B站能再出一个第三方登录的库么

### ISSUE THREAD

**Issue by zsn012** [Bilibili/BiliShare#4]
不想用umeng之类的服务了，大B站出了个分享库，请问能再出个3方登录库么，B站出的，用着放心~~

**Comment by Jungerr** [comment]
公司并没有这种需求，所以并没有着手去做。不过，我可以私下搞一个登录库，弄好后我通知你。

**Comment by zsn012** [comment]
10000+个赞b(￣▽￣)d

**Comment by Jungerr** [comment]
采访一下，为什么不想用umeng之类的服务了？

**Comment by ThinWonton** [comment]
同求  通知我一下哦

**Comment by hunji66** [comment]
同求~~
