### ISSUE TITLE
微信分享问题？刷新缓存解决了

### ISSUE THREAD

**Issue by ThinWonton** [Bilibili/BiliShare#6]
你好，请问微信分享功能是不是有问题的？
`
boolean result = mIWXAPI.sendReq(req);
if (!result && getShareListener() != null) {
	getShareListener().onError(getShareMedia(),
			ShareStatusCode.ST_CODE_SHARE_ERROR_SHARE_FAILED,
			new ShareException("sendReq failed"));
}
`
mIWXAPI.sendReq(req); 返回值永远为true，但是页面一闪而过

**Comment by ThinWonton** [comment]
刷新微信缓存解决了

**Comment by haoshou** [comment]
怎么刷新缓存，我把微信的资料清空加卸载了都不行
