### ISSUE TITLE
继续讨论内存泄漏问题

### ISSUE THREAD

**Issue by ThinWonton** [Bilibili/BiliShare#7]
```
很高兴你抽空发布了新版本0.1.04解决内存泄漏问题，非常感谢您的奉献。
不过，实际上，在使用过程中发现了不少于三个内存泄漏issue，您只修复了一个。
```

下面提供一些个人发现的问题和解决方法，并提出一个小小的建议，请勿见怪。
1.  BaseWxShareHandler中的mResultReceiver广播接收器泄漏问题

>  你的本意是：mResultReceiver在init()中进行了注册，并且在release()中进行释放。
> 
> 但现在我们回过来看ShareAttach#share()中的代码，代码原意是：用户进行新一轮分享时，会把上次分享的handler进行release。下面我们来假设这么一种情况，用户进行了微信分享，我们在BaseWxShareHandler#init()时注册了接收广播，并且分享成功，用户现在看到分享成功后，关闭了activity，现在内存泄漏就会出现。因为，根本就没调用release进行广播注销。这也就变成了一个偶然的事件，其实就是ShareAttach#share()糟糕的逻辑所导致的。

`
public void share(Activity activity, SocializeMedia type, BaseShareParam params,
            SocializeListeners.ShareListener listener) {

```
    if (mShareConfiguration == null) {
        throw new IllegalArgumentException(
                "BiliShareConfiguration must be initialized before share");
    }

    if (mCurrentHandler != null) {
        release(mCurrentHandler.getShareMedia());
    }

    mCurrentHandler = ShareHandlerPool.newHandler(activity, type, mShareConfiguration);

    if (mCurrentHandler != null) {
        try {
            mOuterShareListener = listener;

            if (params == null) {
                throw new IllegalArgumentException(("Share param cannot be null"));
            }

            mInnerProxyListener.onStart(type);
            mCurrentHandler.share(params, mInnerProxyListener);

            if (mCurrentHandler.isDisposable()) {
                release(mCurrentHandler.getShareMedia());
            }

        }
        catch (ShareException e) {
            e.printStackTrace();
            mInnerProxyListener.onError(type, e.getCode(), e);
        }
        catch (Exception e) {
            mInnerProxyListener.onError(type, ShareStatusCode.ST_CODE_SHARE_ERROR_EXCEPTION,
                    e);
            e.printStackTrace();
        }
    }
    else {
        mInnerProxyListener.onError(type, ShareStatusCode.ST_CODE_SHARE_ERROR_UNEXPLAINED,
                new Exception("Unknown share type"));
    }
}
```

`
1.  BaseWxShareHandler中的IWXAPI资源未被释放问题

> 没有解决，不管怎么搞都搞不定。

**建议**
1. 使用leakcanary好好观察一下这些泄漏问题。
2. 重构一下代码，尤其是ShareAttach#share()后面的代码，其实在这之前的代码个人来说非常欣赏，后面觉得有点乱。

由于个人水平有限，如有不当之处，请见谅。

**Comment by Jungerr** [comment]
①，分享的结果会先回调到BiliShareAttach里的mInnerProxyListener，mInnerProxyListener的onSuccess()，onError()，onCancel()会调用release()方法。
②，你指出的“用户进行新一轮分享时，会把上次分享的handler进行release”，这个处理是为了确保因为某些不确定性因素导致①中mInnerProxyListener不被回调时，在下一次分享时有机会release掉之前的handler.
③，你指出的BaseWxShareHandler泄露可能是在多进程分享时BaseWXEntryActivity导致泄露，这个我需要定位一下。
④，谢谢你的建议。

**Comment by Jungerr** [comment]
v0.1.07
